services:
  pareto-ui::
    image: ghcr.io/norpactech/pareto-ui:dev
    container_name: pareto-ui
    restart: always
    environment:
      - PLACEHOLDER=dev
    ports:
      - '8088:80'
    networks:
      - pareto_network

networks:
  pareto_network:
    external: true
